### ISSUE TITLE
How do I get the speed of write/rewrite/read/reread ?

### ISSUE THREAD

**Issue by ytZhou** [jtpaulo/dedisbench#1]
I'm a student who is doing the research about the data deduplication recently and I've been reading your privileged paper "DEDISbench: A Benchmark for Deduplicated Storage System". In addition, I also try this tool DEDISbench in LessFS, but I don't know how to get the speed of write/rewrite/read/reread like you present in paper.
I carefully read the manual, but i can't find way to get results. Which parameters should I use?
Thanks!
Following is some test results.
![223233](https://cloud.githubusercontent.com/assets/1811329/6682775/1baaed9a-ccb8-11e4-884e-70ba2b7ef1d3.png)

**Comment by jtpaulo** [comment]
Although I have sent a private reply through e-mail already, I will post here some examples that will help other users of DEDISbench to perform write, rewrite, read and reread tests, with distinct configurations.

First, the flags that you must always use are:

-p or -n<value>             (Peak or Nominal Bench with throughput rate of N operations per second)
-w or -r                        (Write or Read Bench)
-t<value> or -s<value>      (Benchmark duration (-t) in Minutes or amount of data to write (-s) in MB)

Write Test

```
So, if I want to perform a write test with a peak load that uses 4 processes and writes 256 MB in
files with a size of 64MB, I use the following command

./DEDISbench -p -w -s256 -f64 -c4

You get the result in the screen with the throughput and latency for each process ( the default 
number is 4). Note that this test uses the hotspot random pattern, you can choose another with 
the -a flag
```

Rewrite Test

```
For the rewrite operation you have two options:

    - You can use the -e flag to populate the 4 64 MB files with the dd command

        Then you run ./DEDISbench -p -w -s256 -f64 -c4 -e

    - You can run DEDISbench to write realistic content into the files. In this case you use a 
      sequential access pattern (-a flag) to be sure that the benchmark writes the full 
      content of files. In the next command we write 256MB into 4 files with 64MB with a sequential 
      access pattern. The -z flag ensures that temporary files are not removed when the test ends

        ./DEDISbench -p -w -s256 -c4 -f64 -a0 -z

        Then you can run the actual rewrite test with the command:

        ./DEDISbench -p -w -s256 -f64 -c4
```

Read Test:

```
Similarly to the rewrite test you can populate the files for read tests with the two options above. 

    - If you want to populate with DD, the default configuration for the read tests 
    already does it so you just need to run:

        ./DEDISbench -p -r -s256 -f64 -c4

    - If you want to populate the files with DEDISbench

        ./DEDISbench -p -w -s256 -c4 -f64 -a0 -z

        then you need to use the -y flag to disable the DD population and use the 
             files populated with DEDISbench

        ./DEDISbench -p -r -s256 -f64 -c4 -y
```

Reread Test:

```
Just run another read test after the first one. Use the -z flag for the first test so that the 
temporary files are not removed.
```

Finally, if you want to write/read from a block device instead of files you use the -i flag and you do not need the -z flag. Remember to use the -y flag in reads if you do not want the population to be done with the dd command.
